<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('coupons', function (Blueprint $table) {
            $table->id();

            // Unique coupon code (e.g., PD-A3F9K2)
            $table->string('code')->unique();

            // Coupon type
            $table->enum('type', ['manual', 'auto_service', 'auto_amount'])
                ->comment('manual: admin-created, auto_service: service-based reward, auto_amount: amount-based reward');

            // Discount configuration
            $table->enum('discount_type', ['percentage', 'fixed'])
                ->comment('percentage: % off, fixed: PLN amount off');
            $table->decimal('discount_value', 10, 2);

            // Auto-generation conditions (nullable for manual coupons)
            $table->foreignId('condition_service_id')->nullable()
                ->constrained('services')
                ->nullOnDelete()
                ->comment('Service that triggers auto-generation (for auto_service type)');
            $table->decimal('condition_min_amount', 10, 2)->nullable()
                ->comment('Minimum appointment amount that triggers auto-generation (for auto_amount type)');

            // Usage tracking
            $table->unsignedInteger('uses_count')->default(0)
                ->comment('Number of times coupon was used');
            $table->decimal('total_discount_given', 10, 2)->default(0)
                ->comment('Total discount amount given through this coupon');
            $table->unsignedInteger('generated_bookings_count')->default(0)
                ->comment('Number of new bookings generated by this coupon');

            // Influencer relationship (for influencer coupons)
            $table->foreignId('influencer_id')->nullable()
                ->constrained('influencers')
                ->cascadeOnDelete()
                ->comment('Influencer who owns this coupon (if applicable)');

            // Status and validity
            $table->boolean('is_active')->default(true)
                ->comment('Whether coupon can be used');
            $table->timestamp('valid_from')->nullable()
                ->comment('Start date for coupon validity');
            $table->timestamp('valid_until')->nullable()
                ->comment('Expiration date for coupon');
            $table->unsignedInteger('max_uses')->nullable()
                ->comment('Maximum number of times coupon can be used (null = unlimited)');

            $table->timestamps();

            // Indexes for performance
            $table->index('code');
            $table->index(['is_active', 'valid_from', 'valid_until']);
            $table->index('type');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('coupons');
    }
};
